#!/bin/bash

# Docker Hub Setup Guide for Day Planner
# This script explains what you need to do

echo "╔════════════════════════════════════════════════════════════╗"
echo "║         DOCKER HUB AUTO-PUSH SETUP                         ║"
echo "╚════════════════════════════════════════════════════════════╝"
echo ""
echo "✅ NO PAYMENT REQUIRED - Docker Hub free tier is fully functional!"
echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "STEP 1: Create Free Docker Hub Account"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "1. Go to: https://hub.docker.com/signup"
echo "2. Sign up with email/username (completely free)"
echo "3. Verify your email"
echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "STEP 2: Create Personal Access Token"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "1. Go to: https://hub.docker.com/settings/security"
echo "2. Click 'New Access Token'"
echo "3. Name it: 'github-actions' (or anything)"
echo "4. Click 'Generate'"
echo "5. Copy the token (you'll only see it once!)"
echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "STEP 3: Add GitHub Secrets"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "1. Go to your GitHub repo → Settings → Secrets and variables → Actions"
echo "2. Click 'New repository secret'"
echo ""
echo "   SECRET 1:"
echo "   Name: DOCKER_USERNAME"
echo "   Value: your_docker_hub_username"
echo ""
echo "   SECRET 2:"
echo "   Name: DOCKER_PASSWORD"
echo "   Value: (paste the token from Step 2)"
echo ""
echo "3. Click 'Add secret' for each"
echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "STEP 4: Test It!"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "After secrets are added:"
echo "1. Make any change to your repo (or push empty commit)"
echo "2. Go to Actions tab in GitHub"
echo "3. Watch the 'Build and Push to Docker Hub' workflow run"
echo "4. Once done, your image will be at:"
echo "   docker.io/YOUR_USERNAME/day-planner:latest"
echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "STEP 5: Run Anyone's Container"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "Once pushed, anyone can run it:"
echo ""
echo "  docker run -p 8000:8000 YOUR_USERNAME/day-planner:latest"
echo ""
echo "Then visit: http://localhost:8000"
echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "✨ ALL FREE - no credit card, no limits on public images!"
echo ""
